# SPDX-License-Identifier: BSD-3-Clause
[package]
name          = "vermilion-diagnostics"
version       = "0.1.0"
description   = ""
publish       = false
edition       = { workspace = true }
license       = { workspace = true }
rust-version  = { workspace = true }
repository    = { workspace = true }
homepage      = { workspace = true }
documentation = { workspace = true }

[dependencies]
ariadne        = { workspace = true }

crossterm      = { workspace = true, optional = true }
pulldown-cmark = { workspace = true, optional = true }
ratatui        = { workspace = true, optional = true }
schemars       = { workspace = true, optional = true }
serde          = { workspace = true, optional = true }
syntect        = { workspace = true, optional = true }

[dev-dependencies]
criterion = { workspace = true }
test-log  = { workspace = true }

[features]
default = []

serde  = [ "dep:serde" ]
schema = [ "serde", "dep:schemars" ]
pretty-diagnostics = [ "dep:crossterm", "dep:pulldown-cmark", "dep:ratatui", "dep:syntect" ]
