name: 'Vermilion CI'
on:
  push:
    branches-ignore:
      - 'gh-pages'
    paths:
      - '.github/workflows/ci.yml'
      - 'docs/**'
      - 'crates/**'
      - 'editors/**'
      - 'Carrgo.toml'
      - 'Carrgo.lock'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  lint-vermilion:
    name: 'Lint Vermilion'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 'Setup Rust'
        shell: bash
        run: |
          rustup update

      - name: 'Run Clippy'
        shell: bash
        run: |
          cargo clippy

  build-vermilion:
    name: 'Build Vermilion'
    runs-on: ubuntu-latest
    steps:
      - name: 'Initialize Environment'
        shell: bash
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          echo "$HOME/.cargo/bin:$HOME/.local/bin:$PATH" >> $GITHUB_PATH
          echo "GITHUB_WORKSPACE=\"`pwd`\"" >> $GITHUB_ENV

      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 'Setup Rust'
        shell: bash
        run: |
          rustup update
          rustup component add llvm-tools-preview

      - name: 'Install nextest'
        uses: taiki-e/install-action@v2
        with:
          tool: nextest,cargo-llvm-cov

      - name: 'Build Vermilion'
        shell: bash
        run: |
          cargo build --verbose

      - name: 'Test Vermilion'
        shell: bash
        run: |
          cargo llvm-cov nextest
          cargo llvm-cov report --lcov --output-path lcov.info

      - name: 'Codecov Upload'
        if: success() && github.repository == 'shrine-maiden-heavy-industries/vermilion'
        uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
